### ISSUE TITLE
Always returns "set sdk path first"

### ISSUE THREAD

**Issue by osrl** [Jintin/andle#1]
`andle setsdk -p /Users/osrl/Library/Android/sdk`
`andle setsdk --help`
`andle --version`
 returns "set sdk path first"

**Comment by Jintin** [comment]
what is the msg returned with setsdk command?

**Comment by Jintin** [comment]
If correctly, it'll show 'setsdk:/Users/osrl/Library/Android/sdk'
and you'll find a file named 'andle' in your home dir with content
'/Users/osrl/Library/Android/sdk'

**Comment by Jintin** [comment]
Thank you your feedback, I'll find out what is going on ASAP.

**Comment by Jintin** [comment]
You can add one file '.andle' in your home dir with content '/Users/osrl/Library/Android/sdk' for workaround first. 
Thank you your feedback

**Comment by osrl** [comment]
Sorry it didn't work

```
osrl$ pwd
/
osrl$ cat .andle
/Users/osrl/Library/Android/sdk
```

**Comment by osrl** [comment]
```
osrl$ pwd
/
osrl$ cat .andle
/Users/osrl/Library/Android/sdk

**Comment by Jintin** [comment]
Home dir, not Root dir.

**Comment by osrl** [comment]
Yes pardon me. Workaround worked.

**Comment by Jintin** [comment]
You're welcome.
Bug fix at v1.4.2.
Please run below command later
`sudo pip install andle --upgrade`

**Comment by dixonl90** [comment]
I had the same issue with a clean install as of today. Every command i tried reported "set sdk path first". I created the .andle file in my home directory manually with the correct SDK path and it worked.

**Comment by Jintin** [comment]
Ok, I'll check again.

**Comment by Jintin** [comment]
Seems that 1.4.2 is not complete so your download is 1.4.1 still,
please update or reinstall again.
Thank you.

**Comment by dixonl90** [comment]
Can confirm after updating it works as expected. Thanks.
