### ISSUE TITLE
buildToolsVersion suggested to be android-4.4W

### ISSUE THREAD

**Issue by dixonl90** [Jintin/andle#2]
Running the script gives the following line:
`buildToolsVersion: 23.0.2 -> android-4.4W`

This should not be suggested, 23.0.2 is the newest version of the build tools.

**Comment by Jintin** [comment]
does there's a android-4.4W folder in your `sdk/build-tools` folder?
If yes, you can delete it first.
Because the build too version is parse local first and `a` is bigger than `2`.
I can change it the next version.
Thank you for report it.
